# Generated by Django 4.1 on 2023-11-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='census',
            name='group',
            field=models.CharField(default='', max_length=50),
        ),
    ]
