# Generated by Django 4.1 on 2023-12-13 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0004_censusyesno'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='census',
            unique_together={('voting_id', 'voter_id', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='censusbypreference',
            unique_together={('voting_id', 'voter_id', 'group')},
        ),
    ]
