# Generated by Django 4.1 on 2023-12-13 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0005_alter_census_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='censusbypreference',
            unique_together={('voting_id', 'voter_id', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='censusyesno',
            unique_together={('voting_id', 'voter_id', 'group')},
        ),
    ]
