# Generated by Django 4.1 on 2023-12-17 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0006_censusmultichoice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='census',
            options={'verbose_name': 'Census', 'verbose_name_plural': 'Censuses'},
        ),
        migrations.AlterModelOptions(
            name='censusbypreference',
            options={'verbose_name': 'Census By Preference', 'verbose_name_plural': 'Censuses By Preference'},
        ),
        migrations.AlterModelOptions(
            name='censusmultichoice',
            options={'verbose_name': 'Census Multi-Choice', 'verbose_name_plural': 'Censuses Multi-Choice'},
        ),
        migrations.AlterModelOptions(
            name='censusyesno',
            options={'verbose_name': 'Census Yes No', 'verbose_name_plural': 'Censuses Yes No'},
        ),
    ]
