# Generated by Django 4.1 on 2023-12-13 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0006_alter_censusbypreference_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='census',
            unique_together={('voting_id', 'voter_id')},
        ),
        migrations.AlterUniqueTogether(
            name='censusbypreference',
            unique_together={('voting_id', 'voter_id')},
        ),
        migrations.AlterUniqueTogether(
            name='censusyesno',
            unique_together={('voting_id', 'voter_id')},
        ),
    ]
