# Generated by Django 4.1 on 2023-12-13 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0007_alter_census_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='census',
            unique_together={('voting_id', 'voter_id', 'group')},
        ),
    ]
