# Generated by Django 4.1 on 2023-12-13 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0008_alter_census_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='censusbypreference',
            unique_together={('voting_id', 'voter_id', 'group')},
        ),
    ]
