# Generated by Django 4.1 on 2023-11-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_alter_voting_postproc_alter_voting_tally'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='escaños',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='voting',
            name='tallyType',
            field=models.CharField(default='IDENTITY', max_length=200),
        ),
    ]
