# Generated by Django 4.1 on 2023-11-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_voting_escaños_voting_tallytype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='question',
        ),
        migrations.AddField(
            model_name='voting',
            name='questions',
            field=models.ManyToManyField(related_name='votings', to='voting.question'),
        ),
    ]
