# Generated by Django 4.1 on 2023-12-04 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_remove_voting_question_voting_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionoption',
            old_name='question',
            new_name='questions',
        ),
    ]
