# Generated by Django 4.1 on 2023-12-04 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_rename_question_questionoption_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionoption',
            old_name='questions',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='voting',
            old_name='questions',
            new_name='question',
        ),
    ]
