# Generated by Django 4.1 on 2023-11-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_questionyesno_votingyesno_questionoptionyesno'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingbypreference',
            name='escaños',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='votingbypreference',
            name='tallyType',
            field=models.CharField(default='IDENTITY', max_length=200),
        ),
        migrations.AddField(
            model_name='votingyesno',
            name='escaños',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='votingyesno',
            name='tallyType',
            field=models.CharField(default='IDENTITY', max_length=200),
        ),
    ]
