# Generated by Django 4.1 on 2023-12-14 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20180921_1119'),
        ('voting', '0008_votingbypreference_escaños_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionMultiChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VotingMultiChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('tallyType', models.CharField(default='IDENTITY', max_length=200)),
                ('escaños', models.IntegerField(default=10)),
                ('tally', models.JSONField(blank=True, null=True)),
                ('postproc', models.JSONField(blank=True, null=True)),
                ('auths', models.ManyToManyField(related_name='votingsmultichoice', to='base.auth')),
                ('pub_key', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votingmultichoice', to='base.key')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votingmultichoice', to='voting.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOptionMultiChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('option', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multichoice', to='voting.questionmultichoice')),
            ],
        ),
    ]
