# Generated by Django 4.1 on 2023-12-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_rename_questions_questionoption_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='question_option',
            field=models.ManyToManyField(related_name='options', to='voting.questionoption'),
        ),
    ]
