# Generated by Django 4.1 on 2023-12-14 15:49

from django.db import migrations, models
import voting.models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0008_votingbypreference_escaños_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="votingyesno",
            name="mixnet_id",
            field=models.IntegerField(
                default=voting.models.setMixnetId, editable=False
            ),
        ),
    ]
