# Generated by Django 4.1 on 2023-12-14 19:19

from django.db import migrations, models
import voting.models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0009_votingyesno_mixnet_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="votingbypreference",
            name="mixnet_id",
            field=models.IntegerField(
                default=voting.models.setMixnetId, editable=False
            ),
        ),
    ]
