# Generated by Django 4.1 on 2023-12-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0010_remove_voting_question_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='question_option',
            field=models.ManyToManyField(related_name='option_from_voting', to='voting.questionoption'),
        ),
    ]
