# Generated by Django 4.1 on 2023-12-15 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0010_questionoptionmultichoice_multichoice_and_more'),
        ('voting', '0010_votingbypreference_mixnet_id'),
    ]

    operations = [
    ]
