# Generated by Django 4.1 on 2023-12-15 15:28

from django.db import migrations, models
import voting.models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0010_votingbypreference_mixnet_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="voting",
            name="mixnet_id",
            field=models.IntegerField(
                default=voting.models.setMixnetId, editable=False
            ),
        ),
    ]
