# Generated by Django 4.1 on 2023-12-05 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0011_voting_question_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='question_option',
        ),
        migrations.AddField(
            model_name='voting',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_votings', to='voting.questionoption'),
        ),
    ]
