# Generated by Django 4.1 on 2023-12-15 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0011_merge_20231215_1206'),
        ('voting', '0011_voting_mixnet_id'),
    ]

    operations = [
    ]
