# Generated by Django 4.1 on 2023-12-17 15:07

from django.db import migrations, models
import voting.models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0012_merge_0011_merge_20231215_1206_0011_voting_mixnet_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="votingmultichoice",
            name="mixnet_id",
            field=models.IntegerField(
                default=voting.models.setMixnetId, editable=False
            ),
        ),
    ]
