# Generated by Django 4.1 on 2023-12-09 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_votingbypreference_escaños_and_more'),
        ('voting', '0012_remove_voting_question_option_voting_selected_option'),
    ]

    operations = [
    ]
