# Generated by Django 4.1 on 2023-12-17 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0013_alter_question_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionoptionmultichoice',
            name='selected',
        ),
    ]
