# Generated by Django 4.1 on 2023-12-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0014_remove_questionoptionmultichoice_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionoptionmultichoice',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
