# Generated by Django 4.1 on 2023-12-17 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20180921_1119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auth',
            options={'verbose_name': 'Auth', 'verbose_name_plural': 'Auths'},
        ),
        migrations.AlterModelOptions(
            name='key',
            options={'verbose_name': 'Key', 'verbose_name_plural': 'Keys'},
        ),
    ]
