# Generated by Django 4.1 on 2023-11-24 19:02

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_auto_20180921_1522"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoteByPreference",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voting_preference_id", models.PositiveIntegerField()),
                ("voter_preference_id", models.PositiveIntegerField()),
                ("a", base.models.BigBigField()),
                ("b", base.models.BigBigField()),
                ("voted", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
