# Generated by Django 4.1 on 2023-11-27 17:42

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_votebypreference"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoteYN",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voting_yesno_id", models.PositiveIntegerField()),
                ("voter_yesno_id", models.PositiveIntegerField()),
                ("a", base.models.BigBigField()),
                ("b", base.models.BigBigField()),
                ("voted", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
