# Generated by Django 4.1 on 2023-12-14 12:56

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_voteyn'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteMultiChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voting_multichoice_id', models.PositiveIntegerField()),
                ('voter_multichoice_id', models.PositiveIntegerField()),
                ('a', base.models.BigBigField()),
                ('b', base.models.BigBigField()),
                ('voted', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
